In [1]:
import numpy as np


arr=np.array([0,1,2,3,4,5])
print(type(arr))
print(arr)


<class 'numpy.ndarray'>
[0 1 2 3 4 5]


In [2]:
na = np.array([[0,1,2],[3,4,5]])  # 2  x 3 array (괄호의 갯수)
print(na)
print(na*10)

[[0 1 2]
 [3 4 5]]
[[ 0 10 20]
 [30 40 50]]


In [3]:

print(np.iinfo('int16'))


Machine parameters for int16
---------------------------------------------------------------
min = -32768
max = 32767
---------------------------------------------------------------



In [4]:
print(np.iinfo('int64'))

Machine parameters for int64
---------------------------------------------------------------
min = -9223372036854775808
max = 9223372036854775807
---------------------------------------------------------------

